server:
  port: 8997

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.api.controllers
  writer-with-order-by-keys: true

spring:
  application:
    name: Document Intelligence API
  servlet:
    multipart:
      max-file-size: 500MB # Align with Azure maximum
      max-request-size: 500MB # Align with Azure maximum

# Keys should only be for local - MI or WL identity in production.
azure:
  document-intelligence:
    endpoint: ${AZURE_ENDPOINT}
    key: ${AZURE_KEY}

# This would need to be agreed for production rollout
app:
  upload:
    max-file-size: 500MB # Azure maximum
    max-pdf-pages: 2000 # Azure maximum
    max-image-pixels: 100000000 # Align with Azure limits
    min-image-dimension: 50 # Azure minimum
    max-image-dimension: 10000 # Azure maximum
    allowed-types:
      - application/pdf
      - image/png
      - image/jpeg
